test_notice_channel_success (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_notice_channel_success)
Tests sending a NOTICE to a channel where sender is a member. ... ERROR
test_notice_user_success (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_notice_user_success)
Tests sending a NOTICE to another user successfully. ... ERROR
test_privmsg_channel_success (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_privmsg_channel_success)
Tests sending a private message to a channel where sender is a member. ... ERROR
test_privmsg_not_on_channel (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_privmsg_not_on_channel)
Tests sending a private message to a channel where the sender is not a member. ... ERROR
test_privmsg_to_nonexistent_channel (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_privmsg_to_nonexistent_channel)
Tests sending a private message to a non-existent channel. ... ERROR
test_privmsg_to_nonexistent_user (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_privmsg_to_nonexistent_user)
Tests sending a private message to a non-existent user. ... ERROR
test_privmsg_user_success (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_privmsg_user_success)
Tests sending a private message to another user successfully. ... ERROR

======================================================================
ERROR: test_notice_channel_success (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_notice_channel_success)
Tests sending a NOTICE to a channel where sender is a member.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jack/github/ft_irc_dev/irc_tester/tests/irc_tester_utils.py", line 173, in setUp
    self.sock.connect((self.SERVER_HOST, self.SERVER_PORT))
ConnectionRefusedError: [Errno 111] Connection refused

======================================================================
ERROR: test_notice_user_success (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_notice_user_success)
Tests sending a NOTICE to another user successfully.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jack/github/ft_irc_dev/irc_tester/tests/irc_tester_utils.py", line 173, in setUp
    self.sock.connect((self.SERVER_HOST, self.SERVER_PORT))
ConnectionRefusedError: [Errno 111] Connection refused

======================================================================
ERROR: test_privmsg_channel_success (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_privmsg_channel_success)
Tests sending a private message to a channel where sender is a member.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jack/github/ft_irc_dev/irc_tester/tests/irc_tester_utils.py", line 173, in setUp
    self.sock.connect((self.SERVER_HOST, self.SERVER_PORT))
ConnectionRefusedError: [Errno 111] Connection refused

======================================================================
ERROR: test_privmsg_not_on_channel (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_privmsg_not_on_channel)
Tests sending a private message to a channel where the sender is not a member.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jack/github/ft_irc_dev/irc_tester/tests/irc_tester_utils.py", line 173, in setUp
    self.sock.connect((self.SERVER_HOST, self.SERVER_PORT))
ConnectionRefusedError: [Errno 111] Connection refused

======================================================================
ERROR: test_privmsg_to_nonexistent_channel (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_privmsg_to_nonexistent_channel)
Tests sending a private message to a non-existent channel.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jack/github/ft_irc_dev/irc_tester/tests/irc_tester_utils.py", line 173, in setUp
    self.sock.connect((self.SERVER_HOST, self.SERVER_PORT))
ConnectionRefusedError: [Errno 111] Connection refused

======================================================================
ERROR: test_privmsg_to_nonexistent_user (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_privmsg_to_nonexistent_user)
Tests sending a private message to a non-existent user.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jack/github/ft_irc_dev/irc_tester/tests/irc_tester_utils.py", line 173, in setUp
    self.sock.connect((self.SERVER_HOST, self.SERVER_PORT))
ConnectionRefusedError: [Errno 111] Connection refused

======================================================================
ERROR: test_privmsg_user_success (test_privmsg_channelmsg.TestPrivmsgChannelMsg.test_privmsg_user_success)
Tests sending a private message to another user successfully.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jack/github/ft_irc_dev/irc_tester/tests/irc_tester_utils.py", line 173, in setUp
    self.sock.connect((self.SERVER_HOST, self.SERVER_PORT))
ConnectionRefusedError: [Errno 111] Connection refused

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (errors=7)
